# Generated by Django 3.2.4 on 2021-06-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=30)),
                ('numero_calle', models.IntegerField()),
                ('descripcion', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('comprador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pedidos.comprador')),
                ('direccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pedidos.direccion')),
            ],
        ),
    ]
