# Generated by Django 3.2.4 on 2021-06-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='numero_calle',
            new_name='calle_numero',
        ),
    ]
