# Generated by Django 3.2.4 on 2021-06-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_numero_calle_direccion_calle_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='calle_numero',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='codigo',
            field=models.CharField(default='D8CBb67', max_length=20),
        ),
    ]
