# Generated by Django 3.2.4 on 2021-06-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20210613_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='D8B39b4', max_length=20)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('comprador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pedidos.comprador')),
                ('direccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pedidos.direccion')),
            ],
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
