# Generated by Django 3.2.4 on 2021-06-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20210613_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprador',
            old_name='numero',
            new_name='telefono',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(default='1046A8b', max_length=20),
        ),
    ]
