# Generated by Django 3.2.4 on 2021-06-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20210616_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(default='b6faDC8', max_length=20),
        ),
    ]
