# Generated by Django 3.2 on 2021-04-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_categoria_super_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='super_categoria',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
