# Generated by Django 3.2 on 2021-04-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_categoria_super_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='super_categoria',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
