# Generated by Django 3.2 on 2021-05-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20210425_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.TextField(default='', max_length=50),
        ),
    ]
