# Generated by Django 3.2.4 on 2021-06-20 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_producto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='super_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.categoria'),
        ),
    ]
