# Generated by Django 3.2.4 on 2021-06-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproducto',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
