# Generated by Django 3.2.4 on 2021-06-24 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_pedido_entregado'),
        ('pedido_productos', '0002_alter_pedidoproducto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproducto',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_productos', to='pedidos.pedido'),
        ),
    ]
